# Generated by Django 3.1.5 on 2021-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('place', models.ForeignKey('Place', on_delete=models.CASCADE, verbose_name='Место', related_name='pictures')),
            ],
        ),
    ]
