# Generated by Django 3.1.5 on 2021-01-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210128_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['position']},
        ),
    ]
