# Generated by Django 3.1.5 on 2021-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210202_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
