# Generated by Django 3.1.5 on 2021-02-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20210202_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Позиция'),
        ),
    ]
